name: "✨ Feature"
description: "서버와 화면 연결 작업"
labels: ["feature", "backend"]
body:
  - type: textarea
    attributes:
      label: 📄 기능 개요 (Feature Description)
      description: 서버와 연결할 화면 및 컴포넌트의 목적과 역할을 구체적으로 작성해 주세요.
      placeholder: |
        예: 회원가입 화면과 백엔드 API 연결 (POST /api/signup)
    validations:
      required: true

  - type: input
    attributes:
      label: 🧩 연결할 API Endpoint
      description: 해당 화면에서 연결할 API의 엔드포인트를 입력해 주세요.
      placeholder: /api/login
    validations:
      required: true

  - type: input
    attributes:
      label: 📁 프론트엔드 파일 경로
      description: 연결 작업이 필요한 프론트엔드 파일 또는 컴포넌트 경로를 입력해 주세요.
      placeholder: src/pages/LoginPage.jsx
    validations:
      required: true

  - type: input
    attributes:
      label: 🔗 벤치마킹 사이트 URL (Reference URL)
      description: 참고한 사이트나 클론 대상 웹사이트가 있다면 입력해 주세요. 없다면 생략해도 됩니다.
      placeholder: https://www.example.com/login
    validations:
      required: false
